### ISSUE TITLE
ENML to HTML Library

### ISSUE THREAD

**Issue by tyvsmith** [evernote/evernote-sdk-android#22]

**Comment by mrjjwilson** [comment]
Hi, has this idea been abandoned?

**Comment by tyvsmith** [comment]
I'm no longer maintaining this library at Evernote.

**Comment by mrjjwilson** [comment]
ok, thanks for the reply. 
Do you know if anybody is maintaining it? or where I can get more information about it?

**Comment by matthewayne** [comment]
We are currently working on updating the Android SDK and adding Android Studio support.  After the update we will look at adding support for HTML<>ENML conversion.

**Comment by mrjjwilson** [comment]
thanks for the response matt, support for Android Studio and Gradle will be great!

**Comment by vRallev** [comment]
@mrjjwilson There is an EAP in another branch https://github.com/evernote/evernote-sdk-android/tree/android_studio

**Comment by mrjjwilson** [comment]
@vRallev glad it's up, thanks!

**Comment by vRallev** [comment]
Gradle and Android Studio support is now available. You can share HTML with the main Evernote app, which converts it to ENML. You find the corresponding Intent in this library https://github.com/evernote/android-intent

The demo shows how to use this Intent: https://github.com/evernote/android-intent/blob/master/demo/src/main/java/com/evernote/android/intent/demo/MainActivity.java

**Comment by mrjjwilson** [comment]
@vRallev thanks.

I was having an issue back during development in January when I opened a note in Evernote and then tried to view the same note in my app.
I was unable to parse it because ENML markup had been added to the note.

I haven't looked at the demo for Intents yet, but from your comment it sounds like a 1 way relationship.

my app (html) -> evernote app (html -> enml conversion) -> evernote server

if I want to view a note already in enml markup, how would that work?

evernote server (enml) -> my app (fails to parse enml) -> blank screen

**Comment by vRallev** [comment]
You can download a note as HTML: https://github.com/evernote/evernote-sdk-android/blob/master/library/src/main/java/com/evernote/client/android/asyncclient/EvernoteHtmlHelper.java

A demo can be found here: https://github.com/evernote/evernote-sdk-android/blob/master/demo/src/main/java/com/evernote/android/demo/task/GetNoteHtmlTask.java

**Comment by mrjjwilson** [comment]
@vRallev great, thanks i'll check it out.
